### ISSUE TITLE
Set up cloud server

### ISSUE THREAD

**Issue by vasupol11** [SSD2015/TeamSaint4#10]

**Comment by runyasak** [comment]
Set up on heroku
https://damp-sierra-5224.herokuapp.com/

closes issue

**Comment by dtinth** [comment]
Please update the project's description to include the site's URL. :smile:

**Comment by runyasak** [comment]
I've added in README.md.
Is there any problem if our work in submodule.?
The repository is in my account.

**Comment by runyasak** [comment]
I've changed site url to http://128.199.133.130:49172/
Deploy on Digitalocean

closes issue
