### ISSUE TITLE
EL1 Plan Feedback

### ISSUE THREAD

**Issue by dtinth** [SSD2015/TeamSaint4#8]
- Link from README.md is broken.
- The "Website Online" doesn't have any tasks. You can't have a website deployed online without doing something, right? Please add tasks related to 
- No one has been assigned to any task. We want to know who's doing what.
  - Each team member picks up task and assigns to themselves.
  - The project leader assigns tasks to team members.

**Comment by vasupol11** [comment]
- README.md is fixed
- Tasks have been added to milestone 'Website Online'
- All the tasks have been assigned to team members
  Thank you for you feedback!

**Comment by dtinth** [comment]
Good job! :+1:

I'll close this issue, so now please **focus on actually doing these tasks**.

Please be reminded that these tasks should be done **before** March 5th. This means you have about 6 days to complete them, so plan well.

However, don't sacrifice the quality of the work if you can't finish them on time; just do your best. This is just the first iteration and there are several more. In the next iteration you'll have more experience than this iteration. You'll work faster and you'll make better plans.

Cheers.
